
const blogs = [
  {
    title: "The Power of Marketing: Fueling Business Success",
    category: "Power of Marketing",
    date: "March 15, 2024",
    mark: "webmark",
    comments: "5 Comments",
    time: "5 min read",
    img: "https://www.webmarkx.com/assets/DigitalMak1-BuTj6INl.png",
    desc: "Explore how strategic marketing drives brand awareness and customer engagement for sustainable business growth.",
  },
  {
    title: "Unleashing the Power of Social Media Marketing",
    category: "Social Media Marketing",
    date: "February 28, 2024",
    mark: "webmark",
    comments: "3 Comments",
    time: "4 min read",
    img: "https://www.webmarkx.com/assets/SocialMedia1-DzWv9OkS.jpg",
    desc: "Discover how social media marketing builds connections and drives real business impact through engagement.",
  },
  {
    title: "Content Marketing: The Art of Storytelling",
    category: "Content Marketing",
    date: "January 18, 2024",
    mark: "webmark",
    comments: "6 Comments",
    time: "6 min read",
    img: "https://www.webmarkx.com/assets/SEO1-Div2BE9l.jpg",
    desc: "Learn how compelling content builds brand awareness and fosters meaningful customer relationships.",
  },
  {
    title: "Modern Web Development Strategies",
    category: "Web Development",
    date: "December 10, 2023",
    mark: "webmark",
    comments: "2 Comments",
    time: "7 min read",
    img: "https://www.webmarkx.com/assets/WEB_DEV1-BJJnZVqt.jpg",
    desc: "Explore cutting-edge techniques for crafting impactful websites with engaging user experiences.",
  },
  {
    title: "SEO Optimization: Visibility Secrets",
    category: "SEO Optimization",
    date: "November 20, 2023",
    mark: "webmark",
    comments: "9 Comments",
    time: "8 min read",
    img: "https://www.webmarkx.com/assets/SEO1-Div2BE9l.jpg",
    desc: "Master strategic tactics for boosting online visibility through powerful keyword targeting..",
  },
  {
    title: "Marketing Metrics That Actually Matter",
    category: "Power of Marketing",
    date: "November 8, 2023",
    mark: "webmark",
    comments: "3 Comments",
    time: "6 min read",
    img: "https://www.webmarkx.com/assets/DigitalMak2-DKsH2LRF.png",
    desc: "Learn which key performance indicators you should be tracking to measure your marketing success effectively.",
  },
  {
    title: "Social Marketing: Building Digital Communities",
    category: "Social Marketing",
    date: "October 5, 2023",
    mark: "webmark",
    comments: "4 Comments",
    time: "5 min read",
    img: "https://www.webmarkx.com/assets/DigitalMak1-BuTj6INl.png",
    desc: "Amplify brand influence through authentic engagement and community building strategies.",
  },
  {
    title: "Instagram Algorithm Secrets for 2024",
    category: "Social Media Marketing",
    date: "September 14, 2023",
    mark: "webmark",
    comments: "8 Comments",
    time: "5 min read",
    img: "https://www.webmarkx.com/assets/Power_Marketing1-BdnUlIq2.jpg",
    desc: "Learn how to work with Instagram's algorithm to maximize your organic reach and engagement.",
  },
  {
    title: "PPC Marketing: Maximizing ROI",
    category: "PPC Marketing",
    date: "September 5, 2023",
    mark: "webmark",
    comments: "4 Comments",
    time: "5 min read",
    img: "https://www.webmarkx.com/assets/PCP1-BrJYtxEs.jpg",
    desc: "Learn how to drive targeted traffic with precision campaigns and strategic ad placements.",
  },
  {
    title: "Content Strategy for 2024",
    category: "Content Marketing",
    date: "August 30, 2023",
    mark: "webmark",
    comments: "3 Comments",
    time: "5 min read",
    img: "https://www.webmarkx.com/assets/Power_Marketing2-DajxdSTM.jpg",
    desc: "Prepare your content marketing strategy for the coming year with these key insights and trends.",
  },
  {
    title: "Mobile App Development Trends",
    category: "App Development",
    date: "August 12, 2023",
    mark: "webmark",
    comments: "6 Comments",
    time: "6 min read",
    img: "https://www.webmarkx.com/assets/AppDEV1-BgEmgywD.jpg",
    desc: "Discover the latest in creating impactful mobile solutions with powerful functionality.",
  },
  {
    title: "Omnichannel Marketing Strategies for 2024",
    category: "Power of Marketing",
    date: "June 22, 2023",
    mark: "webmark",
    comments: "7 Comments",
    time: "7 min read",
    img: "https://www.webmarkx.com/assets/marketing_strategies1-DEYJY1lP.jpg",
    desc: "Discover how to create seamless customer experiences across all your marketing channels in the coming year.",
  },
  {
    title: "Flutter vs React Native in 2024",
    category: "App Development",
    date: "May 20, 2023",
    mark: "webmark",
    comments: "7 Comments",
    time: "7 min read",
    img: "https://www.webmarkx.com/assets/SocialMedia1-DzWv9OkS.jpg",
    desc: "Comprehensive comparison of the two leading cross-platform app development frameworks.",
  },
  {
    title: "Video Content: The Future of Engagement",
    category: "Content Marketing",
    date: "May 12, 2023",
    mark: "webmark",
    comments: "6 Comments",
    time: "7 min read",
    img: "https://www.webmarkx.com/assets/DigitalMak3-CCw_qzFY.png",
    desc: "Why video content dominates engagement metrics and how to incorporate it into your strategy.",
  },
  {
    title: "LinkedIn Marketing for B2B Growth",
    category: "Social Media Marketing",
    date: "April 5, 2023",
    mark: "webmark",
    comments: "4 Comments",
    time: "6 min read",
    img: "https://www.webmarkx.com/assets/DigitalMak3-CCw_qzFY.png",
    desc: "Powerful strategies to leverage LinkedIn for generating high-quality B2B leads and partnerships.",
  },
  {
    title: "Cause Marketing: Doing Well by Doing Good",
    category: "Social Marketing",
    date: "March 22, 2023",
    mark: "webmark",
    comments: "5 Comments",
    time: "6 min read",
    img: "https://www.webmarkx.com/assets/DigitalMak2-DKsH2LRF.png",
    desc: "How aligning with social causes can benefit both your brand and society simultaneously.",
  },
  {
    title: "Progressive Web Apps: The Future is Here    ",
    category: "Web Development",
    date: "July 8, 2022",
    mark: "webmark",
    comments: "8 Comments",
    time: "9 min read",
    img: "https://www.webmarkx.com/assets/WEB_DEV2-D_x9AfF_.jpg",
    desc: "Why PWAs are revolutionizing user experience and how to implement them in your projects.",
  },
  {
    title: "Voice Search Optimization Strategies",
    category: "SEO Optimization",
    date: "April 15, 202",
    mark: "webmark",
    comments: "4 Comments",
    time: "6 min read",
    img: "https://www.webmarkx.com/assets/PCP1-BrJYtxEs.jpg",
    desc: "How to adapt your SEO strategy for the growing voice search market and smart assistants.",
  },
  {
    title: "Facebook Ads Targeting Strategies",
    category: "PPC Marketing",
    date: "February 18, 2022",
    mark: "webmark",
    comments: "7 Comments",
    time: "7 min read",
    img: "https://www.webmarkx.com/assets/Power_Marketing2-DajxdSTM.jpg",
    desc: "Advanced techniques to refine your Facebook ad targeting and improve conversion rates.",
  },
  {
    title: "App Store Optimization Techniques",
    category: "App Development",
    date: "October 10, 2021",
    mark: "webmark",
    comments: "3 Comments",
    time: "5 min read",
    img: "https://www.webmarkx.com/assets/Power_Marketing2-DajxdSTM.jpg",
    desc: "Proven strategies to improve your app's visibility and downloads in the app stores.",
  },
];

export default blogs;